apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: test-infra
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 1</title>
    </head>
    <body>
        <h1 style="color: blue;">Hi! I am Version1</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  namespace: test-infra
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 2</title>
    </head>
    <body>
        <h1 style="color: green;">Hi! I am Version2</h1>
    </body>
    </html>
